#!/usr/bin/python3

from os import system
import os

os.system("service hostapd restart")
os.system("service dnsmasq restart")
os.system("sleep 1")
os.system("hostapd -B /etc/hostapd/hostapd.conf")
os.system("sleep 1")
os.system("hostapd -B /etc/hostapd/hostapd.conf")
os.system("sleep 2")
os.system("iptables -t nat -A POSTROUTING -j MASQUERADE")
os.system('sh -c "echo 1 > /proc/sys/net/ipv4/ip_forward"')
